Improve errors handling
Insly/identifier-service-phpclient pull request #9
Opened 2021-12-17 12:28 UTC by mtracz

In this PR I refactored handling error responses. From now an exception should be thrown if response status is not 200.
Improved setting up host in `Config()`. From now, it doesn't matter if host is end with `/` or not. Both cases are valid.
Improved `buildHeaders()` method, cause it was not working with PHP 8.0 as expected.
Added tests;

Closes #5 
Closes #7

2021-12-17 12:38 UTC, krzysztofrewak requested changes

2021-12-17 12:38 UTC, krzysztofrewak commented on readme.md
> +            $authorizationHeader = $request?->header("Authorization") ?? "";
There is no $request here.

2021-12-17 12:38 UTC, krzysztofrewak commented on composer.json
> +    "blumilksoftware/codestyle": "^0.7",
Bump it to 0.8.0

2021-12-17 12:38 UTC, krzysztofrewak commented on tests/mocked/ErrorResponseHandlerTest.php
> +        // when
Shouldn't it be given-when-then?

2021-12-17 12:43 UTC, mtracz commented on tests/mocked/ErrorResponseHandlerTest.php
> +        // when
Theoretically, but we cannot move line 89 (expect Exception) after line where the exception is thrown. It won't work.

2021-12-17 12:46 UTC, mtracz commented on readme.md
> +            $authorizationHeader = $request?->header("Authorization") ?? "";
Updated readme with 
```php
$request = request();
```

2021-12-17 12:46 UTC, mtracz commented on composer.json
> +    "blumilksoftware/codestyle": "^0.7",
Bumped

2021-12-18 09:18 UTC, krzysztofrewak commented on readme.md
> +            $authorizationHeader = $request?->header("Authorization") ?? "";
I'd prefer something like this:
```php
        $this->app->bind(Client::class, function (Application $app): Client {
             $request = $app->make(Request::class);
             $authorizationHeader = $request?->header("Authorization") ?? ""; 
```

2021-12-18 09:19 UTC, krzysztofrewak commented on tests/mocked/ErrorResponseHandlerTest.php
> +        // when
Then I think it's really misguiding here. I would remove these comments.

2021-12-18 09:28 UTC, krzysztofrewak requested changes

2021-12-18 09:28 UTC, krzysztofrewak commented on docker/php/Dockerfile
> +;fi
```suggestion
;fi

```

2021-12-18 09:28 UTC, krzysztofrewak commented on src/Config.php
> +    public function setHost(string $host): void
You are changing public method in one of most important classes in the project. Maybe you could leave this optional `$validate` and mark it deprecated and remove in next version?

2021-12-18 09:28 UTC, krzysztofrewak commented on src/DTO/IdentifierService/IdentifierErrorResponse.php
> +     * @param Error[] $errors
```suggestion
     * @param array<Error> $errors
```

We are thinking about implementing some rules from [here](https://github.com/kubawerlos/php-cs-fixer-custom-fixers) into our codestyle package. Then we'd force to use generic array style in PHPDocs, but I think we can start doing it right now.

2021-12-18 09:28 UTC, krzysztofrewak commented on src/DTO/IdentifierService/IdentifierErrorResponse.php
> +    public static function fromResponseContent(array $responseContent, int $statusCode): static
Why won't you create a builder class for that?

2021-12-22 12:58 UTC, mtracz commented on tests/mocked/ErrorResponseHandlerTest.php
> +        // when
Removed comments. Moved expectException to the top

2021-12-22 12:58 UTC, mtracz commented on readme.md
> +            $authorizationHeader = $request?->header("Authorization") ?? "";
Changed

2021-12-22 12:58 UTC, mtracz commented on src/DTO/IdentifierService/IdentifierErrorResponse.php
> +    public static function fromResponseContent(array $responseContent, int $statusCode): static
Added builder class

2021-12-23 12:13 UTC, krzysztofrewak approved these changes

2022-01-04 11:09 UTC, merged